//! Human-meaningful names for detected communities.
//!
//! Community detection produces numbered buckets; a reader needs names. The
//! build pipeline already derives a *deterministic* name per community — its
//! most representative symbol — and every exporter (report, HTML, wiki,
//! callflow) keys its section headings off that name. This module layers an
//! optional LLM pass on top: it summarises each community as a handful of
//! representative member labels, asks the configured model for a 2-5 word
//! plain-language name, and keeps the deterministic name everywhere the model
//! is absent, unreachable, or unhelpful.
//!
//! Three properties are load-bearing and drive most of the design:
//!
//! 1. **Never unlabelled.** Every function here is fail-soft. A missing API
//!    key, a 500, a truncated JSON reply — none of them may drop a community
//!    back to `Community 7`, because the exporters would then render that.
//!    Failures degrade to the heuristic label, never to an error.
//! 2. **Cheap to re-run.** Names are cached by *community content* (the member
//!    labels), not by community id, so re-running after a rebuild that merely
//!    renumbered the communities costs nothing.
//! 3. **Bounded cost.** Real graphs have hundreds of communities. Requests are
//!    batched, concurrency is capped, and trivially small communities are
//!    skipped — their heuristic name (the one symbol they contain) is already
//!    the best possible name.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};

use graphify_core::graph::KnowledgeGraph;
use graphify_core::model::NodeType;
use graphify_extract::semantic::{AuthType, LLMProvider, LLMProviderConfig};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tracing::{debug, warn};

/// Representative member labels sampled per community for the prompt. Enough
/// to characterise a cluster, few enough that ~100 of them fit a 16k context.
const TOP_K_MEMBERS: usize = 12;

/// Individual member labels are truncated to this many characters so one
/// pathological identifier cannot dominate the prompt budget.
const MAX_MEMBER_LABEL: usize = 60;

/// Upper bound on a generated name. Names are section headings, not prose.
const MAX_LABEL_LEN: usize = 80;

/// Communities per LLM call. Sized so one batch fits a 16k context window.
pub const DEFAULT_BATCH_SIZE: usize = 100;

/// Concurrent in-flight LLM requests. Hundreds of communities must not turn
/// into hundreds of simultaneous sockets (or a rate-limit wall).
pub const DEFAULT_MAX_CONCURRENCY: usize = 4;

/// Communities smaller than this keep their heuristic name. A 1-2 node
/// community *is* its hub symbol; paying for a model round trip to rename
/// `parse_config` to "Config Parsing" is not worth the token.
pub const DEFAULT_MIN_COMMUNITY_SIZE: usize = 3;

/// How many times a batch may be halved and retried after an unparseable
/// reply before its communities are left on their heuristic names.
const MAX_SPLIT_DEPTH: usize = 3;

/// Sub-directory of the cache root holding one JSON file per named community.
const CACHE_SUBDIR: &str = "labels";

/// Bumped whenever the prompt or the parsed shape changes, so old entries miss
/// instead of resurrecting names generated by a different prompt.
const CACHE_VERSION: &str = "v1";

/// Sidecar file holding `{cid: name}`, written beside `graph.json`.
///
/// Same filename the Python implementation uses, so a graph labelled by either
/// implementation is readable by the other.
pub const LABELS_SIDECAR: &str = ".graphify_labels.json";

/// Per-node field carrying the community name in `graph.json`.
pub const NODE_LABEL_FIELD: &str = "community_name";

/// Request timeout for a single labelling call.
const REQUEST_TIMEOUT_SECS: u64 = 120;

/// Tuning knobs for [`label_communities`].
#[derive(Debug, Clone)]
pub struct LabelOptions {
    /// Communities per LLM request.
    pub batch_size: usize,
    /// Maximum concurrent requests.
    pub max_concurrency: usize,
    /// Communities below this size keep their heuristic name.
    pub min_community_size: usize,
    /// Representative member labels sampled per community.
    pub top_k: usize,
    /// Where to persist generated names, keyed by community content. `None`
    /// disables caching (used by tests and one-shot runs).
    pub cache_dir: Option<PathBuf>,
}

impl Default for LabelOptions {
    fn default() -> Self {
        Self {
            batch_size: DEFAULT_BATCH_SIZE,
            max_concurrency: DEFAULT_MAX_CONCURRENCY,
            min_community_size: DEFAULT_MIN_COMMUNITY_SIZE,
            top_k: TOP_K_MEMBERS,
            cache_dir: None,
        }
    }
}

/// A community reduced to what the model actually needs to name it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommunitySummary {
    /// Community id, used to correlate the model's reply back to a community.
    pub id: usize,
    /// Full member count (not the number of sampled labels).
    pub size: usize,
    /// Representative member labels, most connected first, deduplicated.
    pub members: Vec<String>,
}

/// What a labelling run did, for the CLI summary.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct LabelReport {
    /// Communities considered.
    pub total: usize,
    /// Names that came back fresh from the model.
    pub llm_named: usize,
    /// Names served from the content cache (no request made).
    pub from_cache: usize,
    /// Communities below `min_community_size`, left on their heuristic name.
    pub skipped_small: usize,
    /// Communities that kept the name they came in with — a previous run's
    /// name if there was one, otherwise the heuristic.
    pub fallback: usize,
    /// Batches whose request or reply failed after retries.
    pub failed_batches: usize,
    /// Whether an LLM was configured at all.
    pub llm_configured: bool,
    /// First failure seen, for a one-line "why" in the CLI output.
    pub first_error: Option<String>,
}

/// A single cached community name.
#[derive(Debug, Serialize, Deserialize)]
struct CachedLabel {
    label: String,
}

// ── Deterministic (LLM-free) labelling ────────────────────────────────────────

/// Deterministic name for one community: its most representative member.
///
/// Mirrors the heuristic the build pipeline applies, so a graph labelled here
/// and a graph labelled during `build` agree when no LLM is configured.
/// Language-plumbing names (`lib`, `mod`, `tests`, fully-qualified paths) are
/// filtered out first — they are the *least* distinguishing thing in a cluster.
/// Ties are broken toward declarations over files, then by label, so the result
/// does not depend on hash iteration order.
fn representative_member(graph: &KnowledgeGraph, nodes: &[String]) -> Option<String> {
    const GENERIC: [&str; 5] = ["lib", "super::*", "main", "mod", "tests"];

    let mut candidates: Vec<_> = nodes
        .iter()
        .filter_map(|id| graph.get_node(id))
        .filter(|n| {
            !GENERIC.contains(&n.label.as_str())
                && !n.label.starts_with("std::")
                && !n.label.starts_with("serde::")
                && !n.label.contains("::")
        })
        .map(|n| (node_type_rank(&n.node_type), n.label.as_str()))
        .collect();
    candidates.sort_by(|a, b| b.0.cmp(&a.0).then_with(|| a.1.cmp(b.1)));

    candidates
        .first()
        .map(|(_, label)| (*label).to_string())
        .or_else(|| {
            // Every member was filtered out (an all-plumbing community): fall
            // back to the lowest-id member so the community still gets a name.
            let mut ids: Vec<&String> = nodes.iter().collect();
            ids.sort();
            ids.first()
                .and_then(|id| graph.get_node(id))
                .map(|n| n.label.clone())
        })
}

/// Priority of a node type when picking a community's representative symbol.
/// Declarations beat modules, modules beat bare files.
fn node_type_rank(node_type: &NodeType) -> u8 {
    match node_type {
        NodeType::Function
        | NodeType::Class
        | NodeType::Struct
        | NodeType::Trait
        | NodeType::Interface => 3,
        NodeType::Module => 1,
        NodeType::File => 0,
        _ => 2,
    }
}

/// Deterministic names for every community — the fallback the LLM pass builds
/// on and degrades to.
///
/// Communities are visited in id order (not hash order) so the `(cid)`
/// disambiguation suffix, appended when two communities pick the same
/// representative symbol, lands on the same community on every run.
pub fn heuristic_labels(
    graph: &KnowledgeGraph,
    communities: &HashMap<usize, Vec<String>>,
) -> BTreeMap<usize, String> {
    let mut cids: Vec<usize> = communities.keys().copied().collect();
    cids.sort_unstable();

    let mut used: HashSet<String> = HashSet::new();
    let mut labels = BTreeMap::new();
    for cid in cids {
        let nodes = &communities[&cid];
        let best =
            representative_member(graph, nodes).unwrap_or_else(|| format!("Community {cid}"));
        let label = if used.contains(&best) {
            format!("{best} ({cid})")
        } else {
            used.insert(best.clone());
            best
        };
        labels.insert(cid, label);
    }
    labels
}

/// Recover names already stored in a loaded graph.
///
/// `graph.json` carries the community name on each node (`community_name`),
/// which is how a name survives a save/load round trip — the node-link format
/// has nowhere else to put it. Reading them back means a second `label` run
/// starts from the previous run's names rather than from scratch.
pub fn labels_from_graph(graph: &KnowledgeGraph) -> BTreeMap<usize, String> {
    let mut labels = BTreeMap::new();

    for info in &graph.communities {
        if let Some(label) = &info.label
            && !label.trim().is_empty()
        {
            labels.insert(info.id, label.trim().to_string());
        }
    }

    for id in graph.node_ids() {
        let Some(node) = graph.get_node(&id) else {
            continue;
        };
        let (Some(cid), Some(name)) = (
            node.community,
            node.extra.get(NODE_LABEL_FIELD).and_then(Value::as_str),
        ) else {
            continue;
        };
        if !name.trim().is_empty() {
            labels.entry(cid).or_insert_with(|| name.trim().to_string());
        }
    }

    labels
}

// ── Prompt construction ───────────────────────────────────────────────────────

/// Reduce communities to prompt-sized summaries, largest first.
///
/// Members are ordered by degree so the sample leads with the cluster's hubs —
/// the nodes that actually say what it is about — and deduplicated
/// case-insensitively so a community of overloads does not spend its whole
/// sample on one name.
pub fn summarize_communities(
    graph: &KnowledgeGraph,
    communities: &HashMap<usize, Vec<String>>,
    top_k: usize,
) -> Vec<CommunitySummary> {
    let mut summaries: Vec<CommunitySummary> = communities
        .iter()
        .map(|(&id, nodes)| {
            let mut ranked: Vec<(usize, &String)> =
                nodes.iter().map(|n| (graph.degree(n), n)).collect();
            ranked.sort_by(|a, b| b.0.cmp(&a.0).then_with(|| a.1.cmp(b.1)));

            let mut seen: HashSet<String> = HashSet::new();
            let mut members = Vec::new();
            for (_, node_id) in ranked {
                let raw = graph
                    .get_node(node_id)
                    .map_or_else(|| node_id.clone(), |n| n.label.clone());
                let trimmed = trim_member_label(&raw);
                if trimmed.is_empty() {
                    continue;
                }
                if seen.insert(trimmed.to_lowercase()) {
                    members.push(trimmed);
                }
                if members.len() >= top_k {
                    break;
                }
            }

            CommunitySummary {
                id,
                size: nodes.len(),
                members,
            }
        })
        .collect();

    summaries.sort_by(|a, b| b.size.cmp(&a.size).then_with(|| a.id.cmp(&b.id)));
    summaries
}

/// Normalise one member label for the prompt: drop the call parens that make
/// `foo()` and `foo` look like two different symbols, then clamp the length on
/// a char boundary (identifiers can be non-ASCII).
fn trim_member_label(raw: &str) -> String {
    let stripped = raw.trim().trim_matches(|c| c == '(' || c == ')').trim();
    stripped.chars().take(MAX_MEMBER_LABEL).collect()
}

/// Communities worth spending a request on: big enough to be ambiguous, and
/// with at least one resolvable member to describe.
pub fn select_candidates(
    summaries: &[CommunitySummary],
    min_community_size: usize,
) -> Vec<CommunitySummary> {
    summaries
        .iter()
        .filter(|s| s.size >= min_community_size && !s.members.is_empty())
        .cloned()
        .collect()
}

/// One prompt line per community: `Community 3: parse, lex, Token`.
fn prompt_line(summary: &CommunitySummary) -> String {
    format!("Community {}: {}", summary.id, summary.members.join(", "))
}

/// The full naming prompt for one batch.
///
/// Kept identical in shape to the Python implementation's prompt: a single
/// user turn, an explicit "JSON object only" instruction, and one line per
/// community. Models drift toward prose when asked for names in isolation; the
/// worked examples and the no-markdown clause are what keep the reply parseable.
pub fn build_prompt(batch: &[CommunitySummary]) -> String {
    let lines: Vec<String> = batch.iter().map(prompt_line).collect();
    format!(
        "You are naming clusters in a knowledge graph. For each community below, \
         return a concise 2-5 word plain-language name describing what it is about \
         (e.g. \"Order Management\", \"Payment Flow\", \"Auth Middleware\"). \
         Respond ONLY with a JSON object mapping the community id (as a string) to \
         its name - no prose, no markdown fences.\n\n{}",
        lines.join("\n")
    )
}

/// Output budget for a batch. A name is ~10 tokens, but models routinely
/// prepend a preamble that eats the completion and truncates the JSON
/// mid-object, so the budget is deliberately generous.
fn max_tokens_for(batch_len: usize) -> u32 {
    (256 + 48 * batch_len).min(8192) as u32
}

// ── Response parsing ──────────────────────────────────────────────────────────

/// Parse a `{cid: name}` reply, tolerating fences, preamble, and truncation.
///
/// Returns only the ids in `cids` — a model that invents community 999 or
/// echoes the prompt is ignored rather than trusted. A reply that yields
/// nothing at all is an error so the caller can split-and-retry the batch.
pub fn parse_label_response(text: &str, cids: &[usize]) -> anyhow::Result<BTreeMap<usize, String>> {
    let cleaned = strip_fences(text);
    let candidate = slice_json_object(&cleaned);

    let parsed: Option<serde_json::Map<String, Value>> = serde_json::from_str(candidate).ok();

    let pairs: HashMap<String, String> = match parsed {
        Some(map) => map
            .into_iter()
            .filter_map(|(k, v)| v.as_str().map(|s| (k, s.to_string())))
            .collect(),
        None => salvage_pairs(candidate),
    };

    if pairs.is_empty() {
        anyhow::bail!(
            "label response is not parseable JSON: {:?}",
            &text.chars().take(120).collect::<String>()
        );
    }

    let mut out = BTreeMap::new();
    for &cid in cids {
        if let Some(raw) = pairs.get(&cid.to_string()) {
            let name = normalize_label(raw);
            if !name.is_empty() {
                out.insert(cid, name);
            }
        }
    }
    Ok(out)
}

/// Drop a leading ```/```json fence and a trailing fence, if present.
fn strip_fences(text: &str) -> String {
    let trimmed = text.trim();
    let without_open = trimmed
        .strip_prefix("```json")
        .or_else(|| trimmed.strip_prefix("```JSON"))
        .or_else(|| trimmed.strip_prefix("```"))
        .unwrap_or(trimmed);
    without_open
        .trim_end()
        .strip_suffix("```")
        .unwrap_or(without_open)
        .trim()
        .to_string()
}

/// Narrow to the outermost `{...}` so a chatty preamble does not defeat the
/// JSON parser.
fn slice_json_object(text: &str) -> &str {
    if text.starts_with('{') {
        return text;
    }
    match (text.find('{'), text.rfind('}')) {
        (Some(start), Some(end)) if end > start => &text[start..=end],
        _ => text,
    }
}

/// Recover the `"<cid>": "<name>"` pairs that *did* arrive from a reply that is
/// not valid JSON.
///
/// A model can truncate mid-object when its completion budget runs out. The
/// whole batch used to fail on such a reply; salvaging the complete pairs
/// labels those communities instead of dropping every one of them.
fn salvage_pairs(text: &str) -> HashMap<String, String> {
    // Built once per call rather than lazily cached: this runs only on the
    // error path, at most a handful of times per run.
    let Ok(re) = regex::Regex::new(r#""?(-?\d+)"?\s*:\s*"((?:[^"\\]|\\.)*)""#) else {
        return HashMap::new();
    };
    re.captures_iter(text)
        .filter_map(|c| {
            Some((
                c.get(1)?.as_str().to_string(),
                c.get(2)?.as_str().to_string(),
            ))
        })
        .collect()
}

/// Flatten a model-provided name into something safe to use as a heading:
/// no control characters, no internal newlines, bounded length.
pub fn normalize_label(raw: &str) -> String {
    let collapsed: String = raw
        .chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect();
    let words: Vec<&str> = collapsed.split_whitespace().collect();
    words
        .join(" ")
        .trim_matches(|c: char| c == '"' || c == '`')
        .chars()
        .take(MAX_LABEL_LEN)
        .collect::<String>()
        .trim()
        .to_string()
}

// ── Content cache ─────────────────────────────────────────────────────────────

/// Cache key for one community's name.
///
/// Deliberately keyed on the *content* (model + sampled member labels) and not
/// on the community id: re-clustering renumbers communities constantly, and a
/// key that included the id would miss on every renumber even though the
/// cluster — and therefore its correct name — is unchanged.
pub fn cache_key(model: &str, summary: &CommunitySummary) -> String {
    let payload = format!("{CACHE_VERSION}\n{model}\n{}", summary.members.join("\n"));
    graphify_cache::content_hash(payload.as_bytes())
}

/// Stable fingerprint of a community's membership, `sha256(sorted ids)`
/// truncated to 16 hex characters.
///
/// Written beside the labels so a later run can tell which communities
/// actually changed and avoid reusing a name that now describes a different
/// set of nodes.
pub fn community_signature(members: &[String]) -> String {
    let mut sorted: Vec<&String> = members.iter().collect();
    sorted.sort();
    let mut payload = Vec::new();
    for id in sorted {
        payload.extend_from_slice(id.as_bytes());
        payload.push(0);
    }
    graphify_cache::content_hash(&payload)
        .chars()
        .take(16)
        .collect()
}

/// Read a cached name, or `None` on any miss (absent, unreadable, corrupt).
pub fn cache_load(cache_dir: &Path, key: &str) -> Option<String> {
    let path = cache_dir.join(CACHE_SUBDIR).join(format!("{key}.json"));
    let raw = std::fs::read_to_string(path).ok()?;
    let entry: CachedLabel = serde_json::from_str(&raw).ok()?;
    let label = normalize_label(&entry.label);
    (!label.is_empty()).then_some(label)
}

/// Write a name to the cache. Best-effort: a failure here costs a request on
/// the next run, nothing more.
pub fn cache_store(cache_dir: &Path, key: &str, label: &str) -> bool {
    let dir = cache_dir.join(CACHE_SUBDIR);
    if std::fs::create_dir_all(&dir).is_err() {
        return false;
    }
    let path = dir.join(format!("{key}.json"));
    let Ok(body) = serde_json::to_string(&CachedLabel {
        label: label.to_string(),
    }) else {
        return false;
    };
    // Write-then-rename so a concurrent reader never sees a half-written file.
    let tmp = path.with_extension("tmp");
    if std::fs::write(&tmp, body).is_err() {
        return false;
    }
    if std::fs::rename(&tmp, &path).is_err() {
        let _ = std::fs::remove_file(&tmp);
        return false;
    }
    true
}

// ── LLM transport ─────────────────────────────────────────────────────────────

#[derive(Serialize)]
struct ChatMessage {
    role: &'static str,
    content: String,
}

#[derive(Serialize)]
struct ChatRequest {
    model: String,
    max_tokens: u32,
    messages: Vec<ChatMessage>,
}

#[derive(Deserialize)]
struct ChatResponse {
    choices: Vec<ChatChoice>,
}

#[derive(Deserialize)]
struct ChatChoice {
    message: ChatChoiceMessage,
}

#[derive(Deserialize)]
struct ChatChoiceMessage {
    content: Option<String>,
}

#[derive(Deserialize)]
struct AnthropicResponse {
    content: Vec<AnthropicBlock>,
}

#[derive(Deserialize)]
struct AnthropicBlock {
    text: Option<String>,
}

/// Send one naming prompt and return the raw completion text.
///
/// This is a plain text-in/text-out call. The extractor's clients cannot be
/// reused directly because they parse their reply into an `ExtractionResult`;
/// only the provider *configuration* is shared.
async fn call_llm(
    prompt: &str,
    max_tokens: u32,
    config: &LLMProviderConfig,
) -> anyhow::Result<String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(REQUEST_TIMEOUT_SECS))
        .build()?;

    match config.provider {
        LLMProvider::Anthropic => {
            let body = json!({
                "model": config.model,
                "max_tokens": max_tokens,
                "messages": [{ "role": "user", "content": prompt }],
            });
            let mut request = client
                .post(format!("{}/v1/messages", config.base_url))
                .header("anthropic-version", "2023-06-01")
                .header("content-type", "application/json")
                .json(&body);
            let key = config.api_key.as_deref().ok_or_else(|| {
                anyhow::anyhow!(
                    "No credentials for Anthropic. Set ANTHROPIC_API_KEY, run `claude login`, \
                     or configure [llm] in graphify-rs.toml"
                )
            })?;
            request = match config.auth_type {
                AuthType::ApiKey => request.header("x-api-key", key),
                AuthType::Bearer => request.header("authorization", format!("Bearer {key}")),
            };

            let response = request.send().await?;
            let status = response.status();
            if !status.is_success() {
                let body = response.text().await.unwrap_or_default();
                anyhow::bail!("Anthropic API returned {status}: {body}");
            }
            let parsed: AnthropicResponse = response.json().await?;
            Ok(parsed
                .content
                .into_iter()
                .find_map(|b| b.text)
                .unwrap_or_default())
        }
        LLMProvider::OpenAI | LLMProvider::Ollama | LLMProvider::OpenAICompatible => {
            let body = ChatRequest {
                model: config.model.clone(),
                max_tokens,
                messages: vec![ChatMessage {
                    role: "user",
                    content: prompt.to_string(),
                }],
            };
            let mut request = client
                .post(format!("{}/chat/completions", config.base_url))
                .header("content-type", "application/json")
                .json(&body);
            if let Some(key) = config.api_key.as_deref() {
                request = request.header("authorization", format!("Bearer {key}"));
            }

            let response = request.send().await?;
            let status = response.status();
            if !status.is_success() {
                let body = response.text().await.unwrap_or_default();
                anyhow::bail!("LLM API at {} returned {status}: {body}", config.base_url);
            }
            let parsed: ChatResponse = response.json().await?;
            Ok(parsed
                .choices
                .into_iter()
                .find_map(|c| c.message.content)
                .unwrap_or_default())
        }
    }
}

/// Result of naming one batch of communities.
struct BatchOutcome {
    labels: BTreeMap<usize, String>,
    error: Option<String>,
}

/// Name one batch, halving and retrying on an unparseable reply.
///
/// A shorter prompt produces a shorter reply, which is less likely to truncate,
/// so halving is a genuine recovery and not just a retry. Transport errors are
/// *not* split-retried — a 401 will not become a 200 on a smaller prompt. The
/// split work is driven off an explicit stack rather than recursion because an
/// async function cannot recurse without boxing every frame.
async fn label_batch(batch: Vec<CommunitySummary>, config: LLMProviderConfig) -> BatchOutcome {
    let mut labels = BTreeMap::new();
    let mut error = None;
    let mut stack: Vec<(Vec<CommunitySummary>, usize)> = vec![(batch, 0)];

    while let Some((mut chunk, depth)) = stack.pop() {
        if chunk.is_empty() {
            continue;
        }
        let prompt = build_prompt(&chunk);
        let cids: Vec<usize> = chunk.iter().map(|c| c.id).collect();

        let reply = match call_llm(&prompt, max_tokens_for(chunk.len()), &config).await {
            Ok(text) => text,
            Err(e) => {
                // Transport/auth failure: no smaller prompt fixes it.
                warn!(error = %e, communities = chunk.len(), "community labeling request failed");
                error.get_or_insert_with(|| e.to_string());
                continue;
            }
        };

        match parse_label_response(&reply, &cids) {
            Ok(named) if !named.is_empty() => labels.extend(named),
            Ok(_) | Err(_) if chunk.len() > 1 && depth < MAX_SPLIT_DEPTH => {
                let right = chunk.split_off(chunk.len() / 2);
                stack.push((right, depth + 1));
                stack.push((chunk, depth + 1));
            }
            Ok(_) => {
                error.get_or_insert_with(|| {
                    format!(
                        "model named none of the {} communities in a batch",
                        cids.len()
                    )
                });
            }
            Err(e) => {
                warn!(error = %e, "unparseable community labeling reply");
                error.get_or_insert_with(|| e.to_string());
            }
        }
    }

    BatchOutcome { labels, error }
}

// ── Orchestration ─────────────────────────────────────────────────────────────

/// Name every community, using `llm` where possible and `existing` (or a fresh
/// heuristic name) everywhere else.
///
/// Never fails and never returns a partial map: the returned `BTreeMap` has one
/// entry for every community in `communities`, because callers write these
/// straight into report headings where a `None` would surface as a hole.
pub async fn label_communities(
    graph: &KnowledgeGraph,
    communities: &HashMap<usize, Vec<String>>,
    existing: &BTreeMap<usize, String>,
    llm: Option<&LLMProviderConfig>,
    opts: &LabelOptions,
) -> (BTreeMap<usize, String>, LabelReport) {
    // Baseline: an existing name if the caller has one, otherwise the
    // deterministic heuristic. Everything below only ever *overrides* this.
    let mut labels = heuristic_labels(graph, communities);
    for (cid, name) in existing {
        if communities.contains_key(cid) && !name.trim().is_empty() {
            labels.insert(*cid, name.trim().to_string());
        }
    }

    let mut report = LabelReport {
        total: communities.len(),
        llm_configured: llm.is_some(),
        ..LabelReport::default()
    };

    let Some(config) = llm else {
        report.fallback = communities.len();
        return (labels, report);
    };

    let summaries = summarize_communities(graph, communities, opts.top_k.max(1));
    let candidates = select_candidates(&summaries, opts.min_community_size);
    report.skipped_small = summaries.len() - candidates.len();

    // Cache pass: serve what we can without touching the network.
    let mut to_request: Vec<CommunitySummary> = Vec::new();
    let mut keys: HashMap<usize, String> = HashMap::new();
    for summary in candidates {
        let key = cache_key(&config.model, &summary);
        if let Some(dir) = opts.cache_dir.as_deref()
            && let Some(cached) = cache_load(dir, &key)
        {
            labels.insert(summary.id, cached);
            report.from_cache += 1;
            continue;
        }
        keys.insert(summary.id, key);
        to_request.push(summary);
    }

    if !to_request.is_empty() {
        let batch_size = opts.batch_size.max(1);
        let batches: Vec<Vec<CommunitySummary>> = to_request
            .chunks(batch_size)
            .map(<[CommunitySummary]>::to_vec)
            .collect();
        debug!(
            batches = batches.len(),
            communities = to_request.len(),
            "requesting community labels"
        );

        let named = run_batches(batches, config, opts.max_concurrency.max(1), &mut report).await;
        for (cid, name) in named {
            if let Some(dir) = opts.cache_dir.as_deref()
                && let Some(key) = keys.get(&cid)
            {
                cache_store(dir, key, &name);
            }
            labels.insert(cid, name);
            report.llm_named += 1;
        }
    }

    report.fallback = report
        .total
        .saturating_sub(report.llm_named + report.from_cache + report.skipped_small);
    (labels, report)
}

/// Run batches with at most `workers` requests in flight, merging results on
/// this task so the label map is never shared across threads.
async fn run_batches(
    batches: Vec<Vec<CommunitySummary>>,
    config: &LLMProviderConfig,
    workers: usize,
    report: &mut LabelReport,
) -> BTreeMap<usize, String> {
    let mut merged = BTreeMap::new();
    let mut pending = batches.into_iter();
    let mut set: tokio::task::JoinSet<BatchOutcome> = tokio::task::JoinSet::new();

    for _ in 0..workers {
        if let Some(batch) = pending.next() {
            set.spawn(label_batch(batch, config.clone()));
        }
    }

    while let Some(joined) = set.join_next().await {
        match joined {
            Ok(outcome) => {
                if let Some(err) = outcome.error {
                    report.failed_batches += 1;
                    report.first_error.get_or_insert(err);
                }
                merged.extend(outcome.labels);
            }
            Err(e) => {
                report.failed_batches += 1;
                report.first_error.get_or_insert_with(|| e.to_string());
            }
        }
        if let Some(batch) = pending.next() {
            set.spawn(label_batch(batch, config.clone()));
        }
    }

    merged
}

// ── Persistence ───────────────────────────────────────────────────────────────

/// Attach names to the in-memory graph so anything reading `CommunityInfo`
/// (`explain`, the MCP server) sees them within this process.
pub fn apply_labels(graph: &mut KnowledgeGraph, labels: &BTreeMap<usize, String>) {
    for info in &mut graph.communities {
        if let Some(name) = labels.get(&info.id) {
            info.label = Some(name.clone());
        }
    }
}

/// Write names to disk beside `graph_path`, returning the files touched.
///
/// Two destinations, because they serve different readers:
///
/// * `graph.json` gets a `community_name` field on each node. This is the only
///   place a name survives a load, since the node-link format has no slot for
///   community metadata — and it is the field the Python implementation writes,
///   so a graph stays readable by both.
/// * `.graphify_labels.json` (plus a `.sig` of per-community membership
///   fingerprints) is the sidecar: a compact `{cid: name}` map for tools that
///   want the names without parsing a multi-megabyte graph, and the signatures
///   let a later run detect that a cid now covers a different community and
///   its saved name is stale.
///
/// `graph.json` is patched in place rather than re-serialised from the loaded
/// `KnowledgeGraph`, so fields this crate does not model (`hyperedges`,
/// `built_at_commit`, extractor-specific node fields) are preserved verbatim.
pub fn persist_labels(
    graph_path: &Path,
    labels: &BTreeMap<usize, String>,
    communities: &HashMap<usize, Vec<String>>,
) -> anyhow::Result<Vec<PathBuf>> {
    let raw = std::fs::read_to_string(graph_path)?;
    let mut doc: Value = serde_json::from_str(&raw)?;

    let mut stamped = 0usize;
    if let Some(nodes) = doc.get_mut("nodes").and_then(Value::as_array_mut) {
        for node in nodes {
            let Some(cid) = node.get("community").and_then(Value::as_u64) else {
                continue;
            };
            if let Some(name) = labels.get(&(cid as usize))
                && let Some(obj) = node.as_object_mut()
            {
                obj.insert(NODE_LABEL_FIELD.to_string(), Value::String(name.clone()));
                stamped += 1;
            }
        }
    }
    debug!(nodes = stamped, "stamped community names onto graph nodes");

    let dir = graph_path.parent().unwrap_or_else(|| Path::new("."));
    write_atomic(graph_path, serde_json::to_string_pretty(&doc)?.as_bytes())?;

    let sidecar = dir.join(LABELS_SIDECAR);
    let as_map: BTreeMap<String, &String> =
        labels.iter().map(|(k, v)| (k.to_string(), v)).collect();
    write_atomic(&sidecar, serde_json::to_vec(&as_map)?.as_slice())?;

    let sig_path = dir.join(format!("{LABELS_SIDECAR}.sig"));
    let sigs: BTreeMap<String, String> = communities
        .iter()
        .map(|(cid, members)| (cid.to_string(), community_signature(members)))
        .collect();
    write_atomic(&sig_path, serde_json::to_vec(&sigs)?.as_slice())?;

    Ok(vec![graph_path.to_path_buf(), sidecar, sig_path])
}

/// Write via a temp file and rename so a crash mid-write cannot leave a
/// truncated `graph.json` behind.
fn write_atomic(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let tmp = path.with_extension("tmp");
    std::fs::write(&tmp, bytes)?;
    if let Err(e) = std::fs::rename(&tmp, path) {
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use graphify_core::confidence::Confidence;
    use graphify_core::model::{GraphEdge, GraphNode};

    fn node(id: &str, label: &str, node_type: NodeType) -> GraphNode {
        GraphNode {
            id: id.into(),
            label: label.into(),
            source_file: "test.rs".into(),
            source_location: None,
            node_type,
            community: None,
            extra: HashMap::new(),
        }
    }

    fn edge(src: &str, tgt: &str) -> GraphEdge {
        GraphEdge {
            source: src.into(),
            target: tgt.into(),
            relation: "calls".into(),
            confidence: Confidence::Extracted,
            confidence_score: 1.0,
            source_file: "test.rs".into(),
            source_location: None,
            weight: 1.0,
            provenance: None,
            extra: HashMap::new(),
        }
    }

    /// Two communities: `{a,b,c}` around hub `a`, and `{x,y,z}` around hub `x`.
    fn sample_graph() -> (KnowledgeGraph, HashMap<usize, Vec<String>>) {
        let mut g = KnowledgeGraph::new();
        for (id, label, ty) in [
            ("a", "parse_config", NodeType::Function),
            ("b", "Config", NodeType::Struct),
            ("c", "config.rs", NodeType::File),
            ("x", "render_html", NodeType::Function),
            ("y", "Template", NodeType::Struct),
            ("z", "html.rs", NodeType::File),
        ] {
            g.add_node(node(id, label, ty)).unwrap();
        }
        for (s, t) in [("a", "b"), ("a", "c"), ("x", "y"), ("x", "z")] {
            g.add_edge(edge(s, t)).unwrap();
        }
        let communities = HashMap::from([
            (0, vec!["a".to_string(), "b".to_string(), "c".to_string()]),
            (1, vec!["x".to_string(), "y".to_string(), "z".to_string()]),
        ]);
        (g, communities)
    }

    fn summary(id: usize, size: usize, members: &[&str]) -> CommunitySummary {
        CommunitySummary {
            id,
            size,
            members: members.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    // ── heuristic fallback ────────────────────────────────────────────────

    #[test]
    fn heuristic_labels_name_every_community() {
        let (g, communities) = sample_graph();
        let labels = heuristic_labels(&g, &communities);
        assert_eq!(labels.len(), 2);
        assert!(labels.values().all(|l| !l.is_empty()));
    }

    #[test]
    fn heuristic_prefers_declarations_over_files() {
        let (g, communities) = sample_graph();
        let labels = heuristic_labels(&g, &communities);
        // `config.rs` is a File and must lose to the Function/Struct members.
        assert_ne!(labels[&0], "config.rs");
        assert_ne!(labels[&1], "html.rs");
    }

    #[test]
    fn heuristic_disambiguates_duplicate_names() {
        let mut g = KnowledgeGraph::new();
        g.add_node(node("a", "handler", NodeType::Function))
            .unwrap();
        g.add_node(node("b", "handler", NodeType::Function))
            .unwrap();
        let communities = HashMap::from([(0, vec!["a".to_string()]), (1, vec!["b".to_string()])]);
        let labels = heuristic_labels(&g, &communities);
        // Lowest cid keeps the bare name; the collision gets a suffix, and the
        // assignment is by cid order so it is the same on every run.
        assert_eq!(labels[&0], "handler");
        assert_eq!(labels[&1], "handler (1)");
    }

    #[test]
    fn heuristic_falls_back_when_every_member_is_plumbing() {
        let mut g = KnowledgeGraph::new();
        g.add_node(node("m", "mod", NodeType::Module)).unwrap();
        let communities = HashMap::from([(4, vec!["m".to_string()])]);
        let labels = heuristic_labels(&g, &communities);
        assert_eq!(labels[&4], "mod");
    }

    #[tokio::test]
    async fn no_llm_keeps_existing_labels_for_every_community() {
        let (g, communities) = sample_graph();
        let existing = BTreeMap::from([(0, "Configuration Loading".to_string())]);
        let (labels, report) =
            label_communities(&g, &communities, &existing, None, &LabelOptions::default()).await;

        assert_eq!(labels.len(), communities.len());
        assert_eq!(labels[&0], "Configuration Loading");
        // Community 1 had no saved name: it must still come back named.
        assert!(!labels[&1].is_empty());
        assert!(!report.llm_configured);
        assert_eq!(report.llm_named, 0);
        assert_eq!(report.fallback, 2);
    }

    #[tokio::test]
    async fn no_llm_never_leaves_a_community_unlabelled() {
        let (g, communities) = sample_graph();
        let (labels, _) = label_communities(
            &g,
            &communities,
            &BTreeMap::new(),
            None,
            &LabelOptions::default(),
        )
        .await;
        for cid in communities.keys() {
            assert!(labels.contains_key(cid), "community {cid} lost its name");
        }
    }

    #[test]
    fn labels_from_graph_reads_the_node_field() {
        let (mut g, _) = sample_graph();
        // Simulate a reloaded graph.json: names live on the nodes.
        let mut n = node("q", "queue", NodeType::Function);
        n.community = Some(7);
        n.extra.insert(
            NODE_LABEL_FIELD.to_string(),
            Value::String("Job Queue".into()),
        );
        g.add_node(n).unwrap();
        let recovered = labels_from_graph(&g);
        assert_eq!(recovered.get(&7).map(String::as_str), Some("Job Queue"));
    }

    // ── prompt construction ───────────────────────────────────────────────

    #[test]
    fn summaries_rank_by_degree_and_are_largest_first() {
        let (g, communities) = sample_graph();
        let summaries = summarize_communities(&g, &communities, 12);
        assert_eq!(summaries.len(), 2);
        // `a` and `x` are the hubs of their communities.
        assert_eq!(summaries[0].members[0], "parse_config");
        assert_eq!(summaries[1].members[0], "render_html");
        assert!(summaries[0].size >= summaries[1].size);
    }

    #[test]
    fn summaries_respect_top_k_and_deduplicate() {
        let mut g = KnowledgeGraph::new();
        for (i, label) in ["run", "Run", "run", "flush"].iter().enumerate() {
            g.add_node(node(&format!("n{i}"), label, NodeType::Function))
                .unwrap();
        }
        let communities = HashMap::from([(0, (0..4).map(|i| format!("n{i}")).collect::<Vec<_>>())]);
        let summaries = summarize_communities(&g, &communities, 12);
        // "run"/"Run"/"run" collapse to one entry; degrees tie, so node id
        // order decides.
        assert_eq!(summaries[0].members, vec!["run", "flush"]);

        let capped = summarize_communities(&g, &communities, 1);
        assert_eq!(capped[0].members.len(), 1);
    }

    #[test]
    fn member_labels_are_trimmed_and_length_clamped() {
        assert_eq!(trim_member_label("  foo()  "), "foo");
        let long = "x".repeat(200);
        assert_eq!(trim_member_label(&long).chars().count(), MAX_MEMBER_LABEL);
        // Multi-byte identifiers must not panic on the length clamp.
        let unicode = "λ".repeat(200);
        assert_eq!(
            trim_member_label(&unicode).chars().count(),
            MAX_MEMBER_LABEL
        );
    }

    #[test]
    fn prompt_lists_one_line_per_community_with_ids() {
        let batch = vec![summary(3, 9, &["parse", "lex"]), summary(5, 4, &["render"])];
        let prompt = build_prompt(&batch);
        assert!(prompt.contains("2-5 word"), "instruction missing");
        assert!(prompt.contains("JSON object"), "output contract missing");
        assert!(prompt.contains("Community 3: parse, lex"));
        assert!(prompt.contains("Community 5: render"));
        // Ids in the prompt are what the reply is keyed on, so line order must
        // follow batch order.
        let three = prompt.find("Community 3").unwrap();
        let five = prompt.find("Community 5").unwrap();
        assert!(three < five);
    }

    #[test]
    fn token_budget_grows_with_batch_and_is_capped() {
        assert!(max_tokens_for(1) >= 256);
        assert!(max_tokens_for(10) > max_tokens_for(1));
        assert_eq!(max_tokens_for(10_000), 8192);
    }

    // ── tiny-community skipping ───────────────────────────────────────────

    #[test]
    fn candidates_skip_communities_below_the_size_floor() {
        let summaries = vec![
            summary(0, 12, &["a", "b"]),
            summary(1, 2, &["c"]),
            summary(2, 3, &["d"]),
        ];
        let picked = select_candidates(&summaries, DEFAULT_MIN_COMMUNITY_SIZE);
        let ids: Vec<usize> = picked.iter().map(|s| s.id).collect();
        assert_eq!(ids, vec![0, 2], "size-2 community should be skipped");
    }

    #[test]
    fn candidates_skip_communities_with_no_describable_members() {
        let summaries = vec![summary(0, 50, &[])];
        assert!(select_candidates(&summaries, 1).is_empty());
    }

    // ── cache ─────────────────────────────────────────────────────────────

    #[test]
    fn cache_key_is_stable_across_runs_and_community_renumbering() {
        let a = summary(0, 10, &["parse", "lex"]);
        let renumbered = summary(42, 10, &["parse", "lex"]);
        assert_eq!(cache_key("m", &a), cache_key("m", &a));
        assert_eq!(
            cache_key("m", &a),
            cache_key("m", &renumbered),
            "a renumbered but unchanged community must still hit the cache"
        );
    }

    #[test]
    fn cache_key_changes_with_content_and_model() {
        let a = summary(0, 10, &["parse", "lex"]);
        let different_members = summary(0, 10, &["parse", "emit"]);
        assert_ne!(cache_key("m", &a), cache_key("m", &different_members));
        assert_ne!(cache_key("m", &a), cache_key("other-model", &a));
    }

    #[test]
    fn cache_round_trips_and_misses_cleanly() {
        let dir = tempfile::tempdir().unwrap();
        let key = cache_key("m", &summary(0, 9, &["parse"]));
        assert!(
            cache_load(dir.path(), &key).is_none(),
            "empty cache must miss"
        );
        assert!(cache_store(dir.path(), &key, "Config Parsing"));
        assert_eq!(
            cache_load(dir.path(), &key).as_deref(),
            Some("Config Parsing")
        );
        assert!(cache_load(dir.path(), "not-a-key").is_none());
    }

    #[test]
    fn corrupt_cache_entry_is_a_miss_not_a_failure() {
        let dir = tempfile::tempdir().unwrap();
        let sub = dir.path().join(CACHE_SUBDIR);
        std::fs::create_dir_all(&sub).unwrap();
        std::fs::write(sub.join("deadbeef.json"), "{ not json").unwrap();
        assert!(cache_load(dir.path(), "deadbeef").is_none());
    }

    #[test]
    fn community_signature_ignores_member_order() {
        let a = vec!["x".to_string(), "y".to_string()];
        let b = vec!["y".to_string(), "x".to_string()];
        assert_eq!(community_signature(&a), community_signature(&b));
        assert_ne!(community_signature(&a), community_signature(&["z".into()]));
        assert_eq!(community_signature(&a).len(), 16);
    }

    // ── response parsing ──────────────────────────────────────────────────

    #[test]
    fn parses_plain_json_object() {
        let parsed =
            parse_label_response(r#"{"0": "Auth Middleware", "1": "Job Queue"}"#, &[0, 1]).unwrap();
        assert_eq!(parsed[&0], "Auth Middleware");
        assert_eq!(parsed[&1], "Job Queue");
    }

    #[test]
    fn parses_through_fences_and_preamble() {
        let text = "Sure! Here you go:\n```json\n{\"2\": \"Payment Flow\"}\n```";
        let parsed = parse_label_response(text, &[2]).unwrap();
        assert_eq!(parsed[&2], "Payment Flow");
    }

    #[test]
    fn salvages_pairs_from_a_truncated_reply() {
        // Budget ran out mid-object: the complete pairs are still usable.
        let text = r#"{"0": "Auth Middleware", "1": "Job Que"#;
        let parsed = parse_label_response(text, &[0, 1]).unwrap();
        assert_eq!(parsed[&0], "Auth Middleware");
        assert!(!parsed.contains_key(&1));
    }

    #[test]
    fn ignores_ids_that_were_not_asked_for() {
        let parsed = parse_label_response(r#"{"0": "Kept", "99": "Invented"}"#, &[0]).unwrap();
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[&0], "Kept");
    }

    #[test]
    fn unparseable_reply_is_an_error_so_the_caller_can_retry() {
        assert!(parse_label_response("I cannot help with that.", &[0]).is_err());
        assert!(parse_label_response("", &[0]).is_err());
    }

    #[test]
    fn blank_names_do_not_displace_the_fallback() {
        let parsed = parse_label_response(r#"{"0": "   "}"#, &[0]).unwrap();
        assert!(parsed.is_empty());
    }

    #[test]
    fn normalize_label_flattens_and_clamps() {
        assert_eq!(normalize_label("  Auth\n Middleware \t"), "Auth Middleware");
        assert_eq!(normalize_label("\"Quoted Name\""), "Quoted Name");
        assert!(normalize_label(&"word ".repeat(100)).chars().count() <= MAX_LABEL_LEN);
    }

    // ── persistence ───────────────────────────────────────────────────────

    #[test]
    fn apply_labels_sets_community_info() {
        let mut g = KnowledgeGraph::new();
        g.communities = vec![graphify_core::model::CommunityInfo {
            id: 0,
            nodes: vec!["a".into()],
            cohesion: 1.0,
            label: None,
        }];
        apply_labels(&mut g, &BTreeMap::from([(0, "Auth".to_string())]));
        assert_eq!(g.communities[0].label.as_deref(), Some("Auth"));
    }

    #[test]
    fn persist_writes_node_field_sidecar_and_signatures() {
        let dir = tempfile::tempdir().unwrap();
        let graph_path = dir.path().join("graph.json");
        std::fs::write(
            &graph_path,
            r#"{"directed":false,"nodes":[{"id":"a","label":"A","community":0}],
                "links":[],"hyperedges":[],"built_at_commit":"abc123"}"#,
        )
        .unwrap();

        let labels = BTreeMap::from([(0, "Auth Middleware".to_string())]);
        let communities = HashMap::from([(0, vec!["a".to_string()])]);
        let written = persist_labels(&graph_path, &labels, &communities).unwrap();
        assert_eq!(written.len(), 3);

        let doc: Value =
            serde_json::from_str(&std::fs::read_to_string(&graph_path).unwrap()).unwrap();
        assert_eq!(doc["nodes"][0][NODE_LABEL_FIELD], "Auth Middleware");
        // Fields this crate does not model must survive the rewrite.
        assert_eq!(doc["built_at_commit"], "abc123");

        let sidecar: BTreeMap<String, String> = serde_json::from_str(
            &std::fs::read_to_string(dir.path().join(LABELS_SIDECAR)).unwrap(),
        )
        .unwrap();
        assert_eq!(sidecar["0"], "Auth Middleware");

        let sigs: BTreeMap<String, String> = serde_json::from_str(
            &std::fs::read_to_string(dir.path().join(format!("{LABELS_SIDECAR}.sig"))).unwrap(),
        )
        .unwrap();
        assert_eq!(sigs["0"], community_signature(&["a".to_string()]));
    }

    #[test]
    fn persist_round_trips_back_into_labels_from_graph() {
        let dir = tempfile::tempdir().unwrap();
        let graph_path = dir.path().join("graph.json");
        std::fs::write(
            &graph_path,
            r#"{"directed":false,"multigraph":false,"graph":{},
                "nodes":[{"id":"a","label":"A","source_file":"a.rs","node_type":"function","community":0}],
                "links":[]}"#,
        )
        .unwrap();
        persist_labels(
            &graph_path,
            &BTreeMap::from([(0, "Auth Middleware".to_string())]),
            &HashMap::from([(0, vec!["a".to_string()])]),
        )
        .unwrap();

        let doc: Value =
            serde_json::from_str(&std::fs::read_to_string(&graph_path).unwrap()).unwrap();
        let reloaded = KnowledgeGraph::from_node_link_json(&doc).unwrap();
        assert_eq!(
            labels_from_graph(&reloaded).get(&0).map(String::as_str),
            Some("Auth Middleware"),
        );
    }
}
